name: Android CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Testing fudi-nfc
        run: ./gradlew assembleDebug lint -p fudi-nfc
      - name: Upload fudi-nfc artifact
        uses: actions/upload-artifact@v1
        with:
          name: fudi-nfc-aar
          path: fudi-nfc/build/outputs/aar/fudi-nfc-debug.aar
